# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXWSofVVvW0sgEuAKfFNWRKhPT_BofNc
"""

import pandas as pd

df=pd.read_csv('/content/Salary_Dataset_DataScienceLovers (1).csv')

df.head()

df.info()

df.isnull()

for column in df.columns:
    if df[column].isnull().any():
        if df[column].dtype == 'object':  # Categorical column
            df[column] = df[column].fillna(df[column].mode()[0])
        else:  # Numerical column
            df[column] = df[column].fillna(df[column].mean())
print("Null values after imputation:")
print(df.isnull().sum())



"""### Removing Duplicate Rows"""

print(f"Shape of DataFrame before dropping duplicates: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"Shape of DataFrame after dropping duplicates: {df.shape}")

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns

# Apply LabelEncoder to each categorical column
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print("DataFrame after Label Encoding:")
display(df.head())

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Independent variables (X) shape:", X.shape)
print("Dependent variable (y) shape:", y.shape)
display(X.head())
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
linear_reg_model = LinearRegression()

# Train the model using the training data
linear_reg_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

# Initialize and train Decision Tree Regressor
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)
print("Decision Tree Regressor trained successfully.")

# Initialize and train Random Forest Regressor
random_forest_model = RandomForestRegressor(random_state=42)
random_forest_model.fit(X_train, y_train)
print("Random Forest Regressor trained successfully.")

# Initialize and train K-Nearest Neighbors Regressor
knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)
print("K-Nearest Neighbors Regressor trained successfully.")

# Initialize and train Support Vector Regressor (SVR)
# SVR can be computationally intensive on large datasets, so a small sample might be considered for quick demonstration
# For this demonstration, we'll use the full dataset, but be aware it might take time.
# It's also often beneficial to scale data before using SVM. Let's add a note.
print("Training SVR model... This might take a while for large datasets without scaling.")
# For SVR, it's generally good practice to scale features, but for now, we'll proceed without it to directly fulfill the request.
# If performance is an issue, we can add a preprocessing step for scaling later.
svr_model = SVR()
svr_model.fit(X_train, y_train)
print("Support Vector Regressor trained successfully.")

from sklearn.metrics import r2_score, mean_squared_error

models = {
    "Linear Regression": linear_reg_model,
    "Decision Tree": decision_tree_model,
    "Random Forest": random_forest_model,
    "K-Nearest Neighbors": knn_model,
    "Support Vector Machine": svr_model
}

results = {}

for name, model in models.items():
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    results[name] = {"R-squared": r2, "MSE": mse}

print("\n--- Model Performance Evaluation ---")
for name, metrics in results.items():
    print(f"\n{name}:")
    print(f"  R-squared: {metrics['R-squared']:.4f}")
    print(f"  Mean Squared Error (MSE): {metrics['MSE']:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Identify the best performing model based on R-squared
best_model_name = max(results, key=lambda k: results[k]['R-squared'])
best_model = models[best_model_name]

# Make predictions using the best model
y_pred_best_model = best_model.predict(X_test)

# Create a scatter plot of actual vs. predicted values
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_best_model, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual Salary")
plt.ylabel("Predicted Salary")
plt.title(f"Actual vs. Predicted Salary for {best_model_name} Model")
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Loop through each model to create individual plots
for name, model in models.items():
    y_pred = model.predict(X_test)
    r2 = results[name]['R-squared']
    mse = results[name]['MSE']

    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
    plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
    plt.xlabel("Actual Salary")
    plt.ylabel("Predicted Salary")
    plt.title(f"Actual vs. Predicted Salary for {name} Model\nR-squared: {r2:.4f}, MSE: {mse:.2f}")
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

import pandas as pd

# Convert the results dictionary to a DataFrame for better comparison
performance_df = pd.DataFrame(results).T

print("\n--- Model Performance Comparison ---")
display(performance_df.round(4))

# Optionally, you can also sort by R-squared to easily see the best performing model
print("\n--- Model Performance Sorted by R-squared ---")
display(performance_df.sort_values(by='R-squared', ascending=False).round(4))

import pickle

# Define the filename for the pickle file
filename = 'model_performance.pkl'

# Save the performance_df DataFrame to a pickle file
performance_df.to_pickle(filename)

print(f"Performance metrics saved to {filename}")

# Step 1: Install Streamlit and localtunnel



"""Next, we will save the `best_model` (Linear Regression) and the `label_encoders` to pickle files. The Streamlit app will load these files to make predictions and preprocess user inputs."""

import pickle

# Save the best model (Linear Regression)
best_model_name = max(results, key=lambda k: results[k]['R-squared'])
best_model = models[best_model_name]
with open('linear_regression_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)
print(f"Best model ({best_model_name}) saved to linear_regression_model.pkl")

# Save the label_encoders dictionary
with open('label_encoders.pkl', 'wb') as f:
    pickle.dump(label_encoders, f)
print("Label encoders saved to label_encoders.pkl")

"""Now, let's create the Streamlit application file (`app.py`). This file will contain the logic for the web interface, loading the model and encoders, taking user input, and displaying predictions."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import pickle
# 
# # Load the trained model
# with open('linear_regression_model.pkl', 'rb') as f:
#     model = pickle.load(f)
# 
# # Load the label encoders
# with open('label_encoders.pkl', 'rb') as f:
#     label_encoders = pickle.load(f)
# 
# st.title('Salary Prediction App')
# st.write('Enter the details below to predict the salary:')
# 
# # Input fields for features
# rating = st.slider('Rating', 0.0, 5.0, 3.8)
# company_name = st.text_input('Company Name', 'Google')
# job_title = st.text_input('Job Title', 'Software Engineer')
# salaries_reported = st.number_input('Salaries Reported', min_value=1, value=3)
# location = st.text_input('Location', 'Bangalore')
# employment_status = st.selectbox('Employment Status', ['Full Time', 'Contract', 'Part Time', 'Internship'], index=0)
# job_roles = st.text_input('Job Roles', 'Engineering')
# 
# # Create a DataFrame from inputs
# input_data = pd.DataFrame({
#     'Rating': [rating],
#     'Company Name': [company_name],
#     'Job Title': [job_title],
#     'Salaries Reported': [salaries_reported],
#     'Location': [location],
#     'Employment Status': [employment_status],
#     'Job Roles': [job_roles]
# })
# 
# # Preprocess categorical features using loaded LabelEncoders
# for col, encoder in label_encoders.items():
#     # Handle new categories: if a category is not in the encoder's classes, assign a default value or handle it as unknown
#     # For simplicity, we'll try to fit_transform, if it fails due to unknown categories,
#     # we might need a more robust strategy (e.g., add to encoder, or use default like -1)
#     try:
#         input_data[col] = encoder.transform(input_data[col])
#     except ValueError:
#         # If a category is new, we need to handle it. A simple approach is to map it to a new, consistent value
#         # However, for a production app, retraining the encoder with new data or a more sophisticated handling is needed.
#         # For this demo, let's assume valid inputs or handle with a warning.
#         st.warning(f"New category detected in '{col}'. This might affect prediction accuracy.")
#         # A robust way would be to extend the encoder or assign a placeholder value.
#         # For now, let's just make sure it doesn't crash by mapping new values if possible.
#         # This part requires careful consideration depending on the expected input data.
#         # For demonstration, we'll assign a placeholder like 0 or use the existing logic for now.
#         input_data[col] = input_data[col].apply(lambda x: encoder.transform([x])[0] if x in encoder.classes_ else -1)
# 
# if st.button('Predict Salary'):
#     try:
#         prediction = model.predict(input_data)
#         st.success(f'The predicted salary is: ₹{prediction[0]:,.2f}')
#     except Exception as e:
#         st.error(f"An error occurred during prediction: {e}")
#

"""Finally, we will run the Streamlit application. This will launch a web interface where you can interact with the deployed model. A localtunnel URL will be provided to access the app."""

!streamlit run app.py & npx localtunnel --port 8501
